DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
  department_id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR2(255) NOT NULL DEFAULT '',
  manager_employee_id BIGINT NOT NULL DEFAULT 9999,
  PRIMARY KEY (department_id)
);


DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
  employee_id BIGINT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR2(255) NOT NULL DEFAULT '',
  last_name VARCHAR2(255) NOT NULL DEFAULT '',
  title VARCHAR2(255) NOT NULL DEFAULT '',
  phone_number VARCHAR2(255) NOT NULL DEFAULT '',
  email VARCHAR2(255) NOT NULL DEFAULT '',
  hire_date VARCHAR2(255) NOT NULL DEFAULT '',
  manager_employee_id BIGINT DEFAULT 9999,
  department_id BIGINT NOT NULL DEFAULT 9999,
  PRIMARY KEY (employee_id)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;